#!/bin/bash

read -p "Introduce un nombre en minúsculas (sin números ni caracteres especiales salvo -) [mic]: " name

# Comprobamos si el nombre está vacío y le asignamos el valor 'default' por defecto.
if [ -z "$name" ]; then
  name="mic"
fi

# Comprobamos si el nombre contiene solo caracteres en minúsculas y no contiene números ni caracteres especiales.
if ! [[ "$name" =~ ^[a-z-]+$ ]]; then
  echo "El nombre debe contener solo caracteres en minúsculas y sin números ni caracteres especiales."
  exit 1
fi

touch .env

echo "NETWORK=$name" >> .env
echo "NETWORK='$name' guardado en el fichero .env"
echo "Creando red de docker '$name'..."
docker network create -d bridge $name
echo "Configuracion completada"
