#!/bin/bash

keyFile=mic.key
configFile=openssl.conf
csrFile=mic.csr
certFile=mic.crt

# Create the private key
bash aux-scripts/create-private-key $keyFile
if [ $? -ne 0 ]; then
  exit 1
fi
# Create the OpenSSL configuration file
bash aux-scripts/create-openssl-conf $configFile
if [ $? -ne 0 ]; then
  rm $keyFile
  exit 1
fi
# Make the certificate signing request
bash aux-scripts/create-request $keyFile $configFile $csrFile
if [ $? -ne 0 ]; then
  rm $keyFile
  rm $configFile
  exit 1
fi
# Sign the request with the CA certificate and private key
bash aux-scripts/call-sign-request $csrFile $configFile $certFile
if [ $? -ne 0 ]; then
  rm $keyFile
  rm $configFile
  rm $csrFile
  exit 1
fi

mv $certFile ../
mv $keyFile  ../
rm $csrFile
rm $configFile
