#!/bin/bash

# Check 2 arguments are provided
if [ $# -ne 3 ]; then
  echo "Usage: $0 <key> <config> <out>"
  exit 1
fi

# Check first argument is a file
if [ ! -f $1 ]; then
  echo "Error: $1 is not a file"
  exit 1
fi

# Check second argument is a file
if [ ! -f $2 ]; then
  echo "Error: $2 is not a file"
  exit 1
fi

# Generate certificate signing request with openssl conf
openssl req -new -key $1 -out $3 -config $2

# Check if request was generated
if [ $? -ne 0 ]; then
  echo "Error: Failed to generate certificate signing request"
  exit 1
fi

echo "Certificate signing request generated successfully"