{
 "title": "Cell1Main",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "VerdeOscuroBorde", "query": "#b0dab238" },
   { "name": "VerdeOscuroBackground", "query": "#46bd5029" },
   { "name": "VerdeClaroBorde", "query": "#b0dab2" },
   { "name": "VerdeClaroBackground", "query": "#46bd50" },
   { "name": "AzulClaroBorde", "query": "#1c66c6" },
   { "name": "AzulClaroBackground", "query": "#0074ff66" },
   { "name": "AzulOscuroBorde", "query": "#19509636" },
   { "name": "AzulOscuroBackground", "query": "#7a9dc74" },
   { "name": "RojoClaroBorde", "query": "#ee0000bd" },
   { "name": "RojoClaroBackground", "query": "#931f1fb8" },
   { "name": "RojoOscuroBorde", "query": "#df797936" },
   { "name": "RojoOscuroBackground", "query": "#eb000012" },
   { "name": "graph_type", "query": "oee" }
  ]
 },
 "panels": [
  {
   "title": "Average ${graph_type} evolution",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1),  \r\n    CASE \r\n      WHEN '${graph_type}' = 'oee' AND SUM(pbt) <> 0 AND SUM(apt) <> 0 AND SUM(gq+sq) <> 0 THEN ( (SUM(apt) / SUM(pbt)) * (SUM(pru * (gq+sq)) / SUM(apt)) * (SUM(gq) / SUM(gq+sq)) )\r\n      WHEN '${graph_type}' = 'availability' AND SUM(pbt) <> 0 THEN SUM(apt) / SUM(pbt)\r\n      WHEN '${graph_type}' = 'performance' AND SUM(apt) <> 0 THEN SUM(pru * (gq+sq)) / SUM(apt)\r\n      WHEN '${graph_type}' = 'quality' AND SUM(gq+sq) <> 0 THEN SUM(gq) / SUM(gq+sq)\r\n      ELSE NULL  \r\n    END AS metric_value\r\nFROM data_value \r\nINNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3)\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN ( SUM(pbt) <> 0 AND SUM(apt) <> 0 AND SUM(gq+sq) <> 0 ) THEN ( (SUM(apt) / SUM(pbt)) * (SUM(pru * (gq+sq)) / SUM(apt)) * (SUM(gq) / SUM(gq+sq)) ) ELSE NULL END AS OEE \r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 12, "y": 0 },
   "options": {
    "content": "<style>\r\n  .container { display: flex; justify-content: center; align-items: center; }\r\n  .h1_style { text-align: center; font-weight: bold; font-size: 40px; }\r\n  .equal_style { font-size: 70px; }\r\n</style>\r\n\r\n\r\n<br/><br/><br/>\r\n<div class=\"container\">\r\n  <h1 class=\"equal_style\">=</h1>\r\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN SUM(pbt) <> 0 THEN SUM(apt) / SUM(pbt) ELSE NULL END AS AVAILABILITY\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 16, "y": 0 },
   "options": {
    "content": "<br/><br/><br/><br/>\r\n<div class=\"container\">\r\n  <h1 class=\"h1_style\">X</h1>\r\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN SUM(apt) <> 0 THEN SUM(pru * (gq+sq)) / SUM(apt) ELSE NULL END AS EFFECTIVENESS\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 20, "y": 0 },
   "options": {
    "content": "<br/><br/><br/><br/>\r\n<div class=\"container\">\r\n  <h1 class=\"h1_style\">X</h1>\r\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Quality",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN SUM(gq+sq) <> 0 THEN SUM(gq) / SUM(gq+sq) ELSE NULL END AS QUALITY_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\n"
    }
   ]
  },
  {
   "title": "Performance grouped by  Part Number",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\t\tph.part_number_id AS CODE,\r\n\t\tCONCAT(LPAD(FLOOR(AVG(dv.apt) / 3600)::VARCHAR,'2','0'), ':', LPAD(FLOOR((AVG(dv.apt) % 3600) / 60)::VARCHAR, '2', '0')) AS AVG_PROD_TIME,\r\n\t\t((sum(dv.gq) + sum(dv.sq))::INTEGER)::VARCHAR AS TOTAL,\r\n\t\t(sum(dv.gq)::INTEGER)::VARCHAR AS GOOD,\r\n\t\t(sum(dv.sq)::INTEGER)::VARCHAR AS SCRAP,\r\n\t\tCASE WHEN (sum(dv.gq) + sum(dv.sq) <> 0) THEN CONCAT ((((sum(dv.gq) / (sum(dv.gq) + sum(dv.sq)) * 100)::INTEGER)::VARCHAR) , '') ELSE NULL END AS GOOD_PERC\r\nFROM phase AS ph INNER JOIN data_value AS dv ON ph.phase_id = dv.phase_id\r\nWHERE dv.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\nGROUP BY ph.part_number_id\r\nORDER BY ph.part_number_id ASC"
    }
   ]
  },
  {
   "title": "C21-2",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 13 },
   "options": {
    "content": "<img \r\n  src=\"/public/machine-img/maquina1.png\" \r\n  alt=\"Falta la imagen adecuada a esta máquina\" \r\n  width=100%\r\n  height=100%\r\n>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 13 },
   "options": {
    "content": "<style>\n  .circle {\n\twidth: 40px;\n\theight: 40px;\n\tmargin: 5px;\n\tborder-radius: 50%;\n\tborder: 10px solid gray;\n\toverflow: hidden;\n\tdisplay: flex;\n\tjustify-content: center;\n\talign-items: center;\n\tbox-shadow: 0 0 3px gray;\n\t}\n\n  .circle-content {\n\ttext-align: center;\n\tcolor: #fff;\n\tfont-family: Verdana;\n\tfont-size: 1em;\n\tfont-weight: bold;\n\ttext-decoration: none;\n\tdisplay: block;\n\t}\n\n  .empty {\n\tborder: 10px solid transparent;\n\tbox-shadow: none !important;\n\t}\n</style>\n\n<br>\n<div style=\"display: flex; flex-wrap: wrap; justify-content: space-evenly; align-items: center; align-content: stretch;\">\n\t<div>\n\t\t<div class=\"circle on-1\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/on.png\" style=\"max-width: 100%; max-height: 100%\"/>\n\t\t\t</span>\n\t\t</div>\n\t\t<br>\n\t\t<div class=\"circle check-1\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/check.png\" style=\"max-width: 50%; max-height: 50%\"/>\n\t\t\t</span>\n\t\t</div>\n\t</div>\n\t<div>\n\t\t<div class=\"circle redo-1\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/cog.png\" style=\"max-width: 50%; max-height: 50%\"/>\n\t\t\t</span>\n\t\t</div>\n\t\t<br>\n\t\t<div class=\"circle danger-1\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/exclamacion.png\" style=\"max-width: 45%; max-height: 45%\"/>\n\t\t\t</span>\n\t\t</div>\n\t</div>\n</div>\n\n<script>\n    document.querySelector(\".on-1\").style.border = \"10px solid ${VerdeClaroBorde}\";\n    document.querySelector(\".on-1\").style.background = \"${VerdeClaroBackground}\";\n    document.querySelector(\".check-1\").style.border = \"10px solid ${VerdeClaroBorde}\";\n    document.querySelector(\".check-1\").style.background = \"${VerdeClaroBackground}\";\n    document.querySelector(\".redo-1\").style.border = \"10px solid ${AzulOscuroBorde}\";\n    document.querySelector(\".redo-1\").style.background = \"${AzulOscuroBackground}\";\n    document.querySelector(\".danger-1\").style.border = \"10px solid ${RojoOscuroBorde}\";\n    document.querySelector(\".danger-1\").style.background = \"${RojoOscuroBackground}\";\n</script>"
   },
   "targets": [
    { "table": "data_value" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN ( SUM(pbt) <> 0 AND SUM(apt) <> 0 AND SUM(gq+sq) <> 0 ) THEN ( (SUM(apt) / SUM(pbt)) * (SUM(pru * (gq+sq)) / SUM(apt)) * (SUM(gq) / SUM(gq+sq)) ) ELSE NULL END AS OEE \r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id = 1 AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\n"
    }
   ]
  },
  {
   "title": "C21",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 13 },
   "options": {
    "content": "<img \n  src=\"/public/machine-img/maquina2.png\" \n  alt=\"Falta la imagen adecuada a esta máquina\" \n  width=100%\n  height=100%\n>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 13 },
   "options": {
    "content": "<br>\n<div style=\"display: flex; flex-wrap: wrap; justify-content: space-evenly; align-items: center; align-content: stretch;\">\n\t<div>\n\t\t<div class=\"circle on-2\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/on.png\" style=\"max-width: 100%; max-height: 100%\"/>\n\t\t\t</span>\n\t\t</div>\n\t\t<br>\n\t\t<div class=\"circle check-2\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/check.png\" style=\"max-width: 50%; max-height: 50%\"/>\n\t\t\t</span>\n\t\t</div>\n\t</div>\n\t<div>\n\t\t<div class=\"circle redo-2\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/cog.png\" style=\"max-width: 50%; max-height: 50%\"/>\n\t\t\t</span>\n\t\t</div>\n\t\t<br>\n\t\t<div class=\"circle danger-2\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/exclamacion.png\" style=\"max-width: 45%; max-height: 45%\"/>\n\t\t\t</span>\n\t\t</div>\n\t</div>\n</div>\n\n<script>\n    document.querySelector(\".on-2\").style.border = \"10px solid ${VerdeClaroBorde}\";\n    document.querySelector(\".on-2\").style.background = \"${VerdeClaroBackground}\";\n    document.querySelector(\".check-2\").style.border = \"10px solid ${VerdeOscuroBorde}\";\n    document.querySelector(\".check-2\").style.background = \"${VerdeOscuroBackground}\";\n    document.querySelector(\".redo-2\").style.border = \"10px solid ${AzulClaroBorde}\";\n    document.querySelector(\".redo-2\").style.background = \"${AzulClaroBackground}\";\n    document.querySelector(\".danger-2\").style.border = \"10px solid ${RojoOscuroBorde}\";\n    document.querySelector(\".danger-2\").style.background = \"${RojoOscuroBackground}\";\n</script>"
   }
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN ( SUM(pbt) <> 0 AND SUM(apt) <> 0 AND SUM(gq+sq) <> 0 ) THEN ( (SUM(apt) / SUM(pbt)) * (SUM(pru * (gq+sq)) / SUM(apt)) * (SUM(gq) / SUM(gq+sq)) ) ELSE NULL END AS OEE \r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id = 2 AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\n"
    }
   ]
  },
  {
   "title": "T12",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 13 },
   "options": {
    "content": "<img \n  src=\"/public/machine-img/maquina3.png\" \n  alt=\"Falta la imagen adecuada a esta máquina\" \n  width=100%\n  height=100%\n>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 13 },
   "options": {
    "content": "<br>\n<div style=\"display: flex; flex-wrap: wrap; justify-content: space-evenly; align-items: center; align-content: stretch;\">\n\t<div>\n\t\t<div class=\"circle on-3\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/off.png\" style=\"max-width: 100%; max-height: 100%\"/>\n\t\t\t</span>\n\t\t</div>\n\t\t<br>\n\t\t<div class=\"circle check-3\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/check.png\" style=\"max-width: 50%; max-height: 50%\"/>\n\t\t\t</span>\n\t\t</div>\n\t</div>\n\t<div>\n\t\t<div class=\"circle redo-3\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/cog.png\" style=\"max-width: 50%; max-height: 50%\"/>\n\t\t\t</span>\n\t\t</div>\n\t\t<br>\n\t\t<div class=\"circle danger-3\">\n\t\t\t<span class=\"circle-content\">\n\t\t\t\t<img src=\"/public/machine-img/exclamacion.png\" style=\"max-width: 45%; max-height: 45%\"/>\n\t\t\t</span>\n\t\t</div>\n\t</div>\n</div>\n\n<script>\n    document.querySelector(\".on-3\").style.border = \"10px solid ${RojoClaroBorde}\";\n    document.querySelector(\".on-3\").style.background = \"${RojoClaroBackground}\";\n    document.querySelector(\".check-3\").style.border = \"10px solid ${VerdeOscuroBorde}\";\n    document.querySelector(\".check-3\").style.background = \"${VerdeOscuroBackground}\";\n    document.querySelector(\".redo-3\").style.border = \"10px solid ${AzulOscuroBorde}\";\n    document.querySelector(\".redo-3\").style.background = \"${AzulOscuroBackground}\";\n    document.querySelector(\".danger-3\").style.border = \"10px solid ${RojoClaroBorde}\";\n    document.querySelector(\".danger-3\").style.background = \"${RojoClaroBackground}\";\n</script>"
   }
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN ( SUM(pbt) <> 0 AND SUM(apt) <> 0 AND SUM(gq+sq) <> 0 ) THEN ( (SUM(apt) / SUM(pbt)) * (SUM(pru * (gq+sq)) / SUM(apt)) * (SUM(gq) / SUM(gq+sq)) ) ELSE NULL END AS OEE \r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id = 3 AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  make_date(year, month_number, 1),\r\n  CASE WHEN ( SUM(pbt) <> 0 AND SUM(apt) <> 0 AND SUM(gq+sq) <> 0 ) THEN ( (SUM(apt) / SUM(pbt)) * (SUM(pru * (gq+sq)) / SUM(apt)) * (SUM(gq) / SUM(gq+sq)) ) ELSE NULL END AS OEE \r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id = 1\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  make_date(year, month_number, 1), \r\n  CASE WHEN ( SUM(pbt) <> 0 AND SUM(apt) <> 0 AND SUM(gq+sq) <> 0 ) THEN ( (SUM(apt) / SUM(pbt)) * (SUM(pru * (gq+sq)) / SUM(apt)) * (SUM(gq) / SUM(gq+sq)) ) ELSE NULL END AS OEE \r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id = 2\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  make_date(year, month_number, 1), \r\n  CASE WHEN ( SUM(pbt) <> 0 AND SUM(apt) <> 0 AND SUM(gq+sq) <> 0 ) THEN ( (SUM(apt) / SUM(pbt)) * (SUM(pru * (gq+sq)) / SUM(apt)) * (SUM(gq) / SUM(gq+sq)) ) ELSE NULL END AS OEE \r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id = 3\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  }
 ]
}