{
 "title": "Cell1KPIs",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "UTILIZATION EFFICIENCY EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(aubt) <> 0 THEN SUM(apt) / SUM(aubt) ELSE NULL END AS UTILIZATION_EFFICIENCY\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3)\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "UTILIZATION EFFICIENCY STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(aubt) <> 0 THEN SUM(apt) / SUM(aubt) ELSE NULL END AS UTILIZATION_EFFICIENCY\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "CORRECTIVE MAINTENANCE RATIO EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN (SUM(cmt) + SUM(pmt)) <> 0 THEN SUM(cmt) / (SUM(cmt) + SUM(pmt)) ELSE NULL END AS CORRECTIVE_MAINTENANCE_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3)\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "CORRECTIVE MAINTENANCE RATIO STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN (SUM(cmt) + SUM(pmt)) <> 0 THEN SUM(cmt) / (SUM(cmt) + SUM(pmt)) ELSE NULL END AS CORRECTIVE_MAINTENANCE_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "AVAILABILITY EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(pbt) <> 0 THEN SUM(apt) / SUM(pbt) ELSE NULL END AS AVAILABILITY\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3)\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "AVAILABILITY STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(pbt) <> 0 THEN SUM(apt) / SUM(pbt) ELSE NULL END AS AVAILABILITY\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "QUALITY RATIO EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(gq+sq) <> 0 THEN SUM(gq) / SUM(gq+sq) ELSE NULL END AS QUALITY_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3)\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "QUALITY RATIO STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(gq+sq) <> 0 THEN SUM(gq) / SUM(gq+sq) ELSE NULL END AS QUALITY_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "EFFECTIVENESS EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(apt) <> 0 THEN SUM(pru * (gq+sq)) / SUM(apt) ELSE NULL END AS EFFECTIVENESS\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3)\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "EFFECTIVENESS STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(apt) <> 0 THEN SUM(pru * (gq+sq)) / SUM(apt) ELSE NULL END AS EFFECTIVENESS\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\nGROUP BY month_number, year\r\nORDER BY month_number\r\n"
    }
   ]
  },
  {
   "title": "SCRAP RATIO EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(gq+sq) <> 0 THEN SUM(sq) / SUM(gq+sq) ELSE NULL END AS SCRAP_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3)\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "SCRAP RATIO STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(gq+sq) <> 0 THEN SUM(sq) / SUM(gq+sq) ELSE NULL END AS SCRAP_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "PRODUCTION PROCESS RATIO EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(aoet) <> 0 THEN SUM(apt) / SUM(aoet) ELSE NULL END AS PRODUCTION_PROCESS_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3)\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "PRODUCTION_PROCESS_RATIO STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(aoet) <> 0 THEN SUM(apt) / SUM(aoet) ELSE NULL END AS PRODUCTION_PROCESS_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "REWORK RATIO EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(gq+sq) <> 0 THEN SUM(rq) / SUM(gq+sq) ELSE NULL END AS REWORK_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3)\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  },
  {
   "title": "REWORK RATIO STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT make_date(year, month_number, 1), CASE WHEN SUM(gq+sq) <> 0 THEN SUM(rq) / SUM(gq+sq) ELSE NULL END AS REWORK_RATIO\r\nFROM data_value INNER JOIN time ON data_value.time_id = time.time_id\r\nWHERE equipment_id IN (1,2,3) AND data_value.time_id BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDD')::INTEGER AND to_char(to_timestamp($__to / 1000), 'YYYYMMDD')::INTEGER\r\nGROUP BY month_number, year\r\nORDER BY month_number"
    }
   ]
  }
 ]
}