{
 "title": "Cell1KPIsPrecalc",
 "time": { "from": "now-1M", "to": "now+6M" },
 "panels": [
  {
   "title": "UTILIZATION EFFICIENCY EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 9 AND object_type = 'c' AND object_id = 1 AND moment BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDDHH24') AND to_char(to_timestamp($__to / 1000), 'YYYYMMDDHH24')\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "UTILIZATION EFFICIENCY STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 9 AND object_type = 'c' AND object_id = 1\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "CORRECTIVE MAINTENANCE RATIO EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 7 AND object_type = 'c' AND object_id = 1 AND moment BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDDHH24') AND to_char(to_timestamp($__to / 1000), 'YYYYMMDDHH24')\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "CORRECTIVE MAINTENANCE RATIO STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 7 AND object_type = 'c' AND object_id = 1\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "AVAILABILITY EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "--SELECT to_timestamp(SUBSTRING(moment from 1 for 10), 'YYYYMMDDHH24'), avg(calc_value)\r\n--FROM stored_kpi\r\n--WHERE kpi_id = 2 AND object_type = 'c' AND object_id = 1\r\n--GROUP BY SUBSTRING(moment from 1 for 10)\r\n--ORDER by SUBSTRING(moment from 1 for 10) ASC\r\n\r\nSELECT to_timestamp(SUBSTRING(moment from 1 for 8), 'YYYYMMDD'), avg(calc_value)\r\nFROM stored_kpi\r\nWHERE kpi_id = 2 AND object_type = 'c' AND object_id = 1\r\nGROUP BY SUBSTRING(moment from 1 for 8)\r\nORDER by SUBSTRING(moment from 1 for 8) ASC"
    }
   ]
  },
  {
   "title": "AVAILABILITY STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 2 AND object_type = 'c' AND object_id = 1\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "QUALITY RATIO EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 4 AND object_type = 'c' AND object_id = 1 AND moment BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDDHH24') AND to_char(to_timestamp($__to / 1000), 'YYYYMMDDHH24')\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "QUALITY RATIO STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 4 AND object_type = 'c' AND object_id = 1\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "EFFECTIVENESS EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 3 AND object_type = 'c' AND object_id = 1 AND moment BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDDHH24') AND to_char(to_timestamp($__to / 1000), 'YYYYMMDDHH24')\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "EFFECTIVENESS STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 3 AND object_type = 'c' AND object_id = 1\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "SCRAP RATIO EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 5 AND object_type = 'c' AND object_id = 1 AND moment BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDDHH24') AND to_char(to_timestamp($__to / 1000), 'YYYYMMDDHH24')\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "SCRAP RATIO STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 5 AND object_type = 'c' AND object_id = 1\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "PRODUCTION PROCESS RATIO EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 8 AND object_type = 'c' AND object_id = 1 AND moment BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDDHH24') AND to_char(to_timestamp($__to / 1000), 'YYYYMMDDHH24')\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "PRODUCTION_PROCESS_RATIO STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 8 AND object_type = 'c' AND object_id = 1\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "REWORK RATIO EVOLUTION",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 6 AND object_type = 'c' AND object_id = 1 AND moment BETWEEN to_char(to_timestamp($__from / 1000), 'YYYYMMDDHH24') AND to_char(to_timestamp($__to / 1000), 'YYYYMMDDHH24')\r\nORDER BY moment ASC"
    }
   ]
  },
  {
   "title": "REWORK RATIO STATUS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(moment, 'YYYYMMDDHH24'), calc_value\r\nFROM stored_kpi\r\nWHERE kpi_id = 6 AND object_type = 'c' AND object_id = 1\r\nORDER BY moment ASC"
    }
   ]
  }
 ]
}